### ISSUE TITLE
Pixelfed logo does not show in Inkscape and imagemagic

### ISSUE THREAD

**Issue by htgoebel** [pixelfed/brand-assets#1]
I tried opening the logo (public/img/pixelfed-icon-color.svg) in inkscape but only got an empty page. Same when I try to display it using ImageMagick's `display´. The logo shows fine in Firefox, though.

**Comment by dansup** [comment]
@htgoebel The logo was created with Sketch, it displays fine in evergreen browsers.

**Comment by hellcp** [comment]
Quick and easy way to fix this? Select the whole canvas with [ctrl] + [A] and press [shift] + [ctrl] + [G] repeatedly to ungroup until it's visible. Anyway, that's annoying, let's fix that in the repo.
